# Generated by Django 6.0 on 2025-12-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_booking_options_remove_booking_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
    ]
